<?php

use App\Controllers\ActivityController;
use App\Controllers\AcquisitionTargetController;
use App\Controllers\AuthController;
use App\Controllers\CapacityRadarController;
use App\Controllers\CrudController;
use App\Controllers\DashboardController;
use App\Controllers\DecisionSupportController;
use App\Controllers\DemandController;
use App\Controllers\HarvesterController;
use App\Controllers\HuntController;
use App\Controllers\OutreachController;
use App\Controllers\PursuitController;
use App\Controllers\RecommendationController;
use App\Controllers\RelationshipController;
use App\Controllers\SignalQualityController;
use App\Controllers\SignalController;
use App\Controllers\SubcontractorAcquisitionController;
use App\Controllers\TrafficController;
use App\Core\Router;

$router = new Router();

$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->get('/', [DashboardController::class, 'index']);
$router->get('/regions', [DashboardController::class, 'regions']);
$router->get('/command/southeast', [DashboardController::class, 'southeast']);
$router->get('/command/great-lakes', [DashboardController::class, 'greatLakes']);
$router->get('/command/southwest', [DashboardController::class, 'southwest']);
$router->get('/harvesters', [HarvesterController::class, 'index']);
$router->post('/harvesters/sources', [HarvesterController::class, 'saveSource']);
$router->post('/harvesters/run', [HarvesterController::class, 'run']);
$router->post('/harvesters/process', [HarvesterController::class, 'process']);
$router->post('/harvesters/import-csv', [HarvesterController::class, 'importCsv']);
$router->get('/targets', [AcquisitionTargetController::class, 'index']);
$router->post('/targets', [AcquisitionTargetController::class, 'save']);
$router->post('/targets/build', [AcquisitionTargetController::class, 'build']);
$router->get('/targets/hunting', [AcquisitionTargetController::class, 'hunting']);
$router->get('/hunting-lists', [AcquisitionTargetController::class, 'hunting']);
$router->get('/targets/detail', [AcquisitionTargetController::class, 'detail']);
$router->post('/targets/status', [AcquisitionTargetController::class, 'status']);
$router->post('/targets/convert', [AcquisitionTargetController::class, 'convert']);
$router->get('/hunts', [HuntController::class, 'index']);
$router->post('/hunts', [HuntController::class, 'saveHunt']);
$router->get('/playbooks', [HuntController::class, 'playbooks']);
$router->post('/playbooks', [HuntController::class, 'savePlaybook']);
$router->post('/playbook-steps', [HuntController::class, 'saveStep']);
$router->post('/hunt-targets', [HuntController::class, 'assignTarget']);
$router->get('/hunt-actions', [HuntController::class, 'actions']);
$router->post('/hunt-tasks/complete', [HuntController::class, 'completeTask']);
$router->post('/hunt-targets/outcome', [HuntController::class, 'outcome']);
$router->get('/traffic', [TrafficController::class, 'index']);
$router->post('/traffic/keywords', [TrafficController::class, 'saveKeyword']);
$router->post('/traffic/content', [TrafficController::class, 'saveContent']);
$router->post('/traffic/outreach', [TrafficController::class, 'saveOutreach']);
$router->post('/traffic/sequences', [TrafficController::class, 'saveSequence']);
$router->get('/demand', [DemandController::class, 'index']);
$router->get('/demand-briefing', [DemandController::class, 'briefing']);
$router->post('/demand/channels', [DemandController::class, 'saveChannel']);
$router->post('/demand/content', [DemandController::class, 'saveContent']);
$router->post('/demand/signals', [DemandController::class, 'saveDemandSignal']);
$router->post('/demand/drafts/review', [DemandController::class, 'reviewDraft']);
$router->post('/demand/distribution/status', [DemandController::class, 'updateDistribution']);
$router->get('/outreach', [OutreachController::class, 'index']);
$router->get('/outreach/southeast', [OutreachController::class, 'southeast']);
$router->get('/outreach/great-lakes', [OutreachController::class, 'greatLakes']);
$router->get('/outreach/southwest', [OutreachController::class, 'southwest']);
$router->get('/outreach/detail', [OutreachController::class, 'detail']);
$router->post('/outreach/rebuild', [OutreachController::class, 'rebuild']);
$router->post('/outreach/scripts/review', [OutreachController::class, 'reviewScript']);
$router->post('/outreach/outcome', [OutreachController::class, 'outcome']);
$router->get('/pursuits', [PursuitController::class, 'index']);
$router->get('/pursuits/southeast', [PursuitController::class, 'southeast']);
$router->get('/pursuits/great-lakes', [PursuitController::class, 'greatLakes']);
$router->get('/pursuits/southwest', [PursuitController::class, 'southwest']);
$router->get('/pursuits/detail', [PursuitController::class, 'detail']);
$router->post('/pursuits/rebuild', [PursuitController::class, 'rebuild']);
$router->get('/decision-support', [DecisionSupportController::class, 'index']);
$router->get('/decision-support/southeast', [DecisionSupportController::class, 'southeast']);
$router->get('/decision-support/great-lakes', [DecisionSupportController::class, 'greatLakes']);
$router->get('/decision-support/southwest', [DecisionSupportController::class, 'southwest']);
$router->get('/daily-brief', [DecisionSupportController::class, 'dailyBrief']);
$router->post('/daily-actions/complete', [DecisionSupportController::class, 'completeAction']);
$router->post('/daily-actions/dismiss', [DecisionSupportController::class, 'dismissAction']);
$router->post('/daily-actions/follow-up', [DecisionSupportController::class, 'followUp']);
$router->get('/capacity', [DashboardController::class, 'capacity']);
$router->get('/relationships', [DashboardController::class, 'relationships']);
$router->get('/opportunity-intelligence', [DashboardController::class, 'opportunityIntelligence']);
$router->get('/signals', [SignalController::class, 'index']);
$router->post('/signals', [SignalController::class, 'save']);
$router->post('/signals/status', [SignalController::class, 'updateStatus']);
$router->post('/signals/convert', [SignalController::class, 'convert']);
$router->get('/watchlists', [SignalQualityController::class, 'watchlists']);
$router->get('/escalations', [SignalQualityController::class, 'escalations']);
$router->get('/briefing', [SignalQualityController::class, 'briefing']);
$router->post('/quality/rebuild', [SignalQualityController::class, 'rebuild']);
$router->get('/capacity-radar', [CapacityRadarController::class, 'index']);
$router->get('/capacity-radar/southeast', [CapacityRadarController::class, 'southeast']);
$router->get('/capacity-radar/great-lakes', [CapacityRadarController::class, 'greatLakes']);
$router->get('/capacity-radar/southwest', [CapacityRadarController::class, 'southwest']);
$router->post('/capacity-radar/rebuild', [CapacityRadarController::class, 'rebuild']);
$router->get('/relationship-graph', [RelationshipController::class, 'index']);
$router->get('/relationship-graph/southeast', [RelationshipController::class, 'southeast']);
$router->get('/relationship-graph/great-lakes', [RelationshipController::class, 'greatLakes']);
$router->get('/relationship-graph/southwest', [RelationshipController::class, 'southwest']);
$router->get('/contacts/detail', [RelationshipController::class, 'contactDetail']);
$router->get('/organizations/detail', [RelationshipController::class, 'organizationDetail']);
$router->post('/relationship-signals/convert', [RelationshipController::class, 'convertSignal']);
$router->post('/relationship-actions/complete', [RelationshipController::class, 'completeAction']);
$router->get('/organizations', [CrudController::class, 'organizations']);
$router->post('/organizations', [CrudController::class, 'saveOrganization']);
$router->post('/delete', [CrudController::class, 'delete']);
$router->get('/contacts', [CrudController::class, 'contacts']);
$router->post('/contacts', [CrudController::class, 'saveContact']);
$router->get('/subcontractors', [CrudController::class, 'subcontractors']);
$router->post('/subcontractors', [CrudController::class, 'saveSubcontractor']);
$router->get('/subcontractor-acquisition', [SubcontractorAcquisitionController::class, 'index']);
$router->get('/subcontractor-acquisition/detail', [SubcontractorAcquisitionController::class, 'detail']);
$router->post('/subcontractor-acquisition/scorecard', [SubcontractorAcquisitionController::class, 'saveScorecard']);
$router->post('/subcontractor-acquisition/compliance', [SubcontractorAcquisitionController::class, 'saveCompliance']);
$router->post('/subcontractor-acquisition/documents', [SubcontractorAcquisitionController::class, 'saveDocument']);
$router->post('/subcontractor-acquisition/promote', [SubcontractorAcquisitionController::class, 'promote']);
$router->get('/opportunities', [CrudController::class, 'opportunities']);
$router->post('/opportunities', [CrudController::class, 'saveOpportunity']);
$router->get('/recommendations', [RecommendationController::class, 'index']);
$router->post('/recommendations', [RecommendationController::class, 'update']);
$router->post('/recommendations/regenerate', [RecommendationController::class, 'regenerate']);
$router->get('/activities', [ActivityController::class, 'index']);
$router->post('/activities', [ActivityController::class, 'save']);
$router->get('/settings', [DashboardController::class, 'settings']);
$router->post('/settings/targets', [DashboardController::class, 'saveTargets']);
$router->get('/record', [ActivityController::class, 'record']);

return $router;
