<section class="page-header"><p class="eyebrow">Capacity Acquisition</p><h1>Subcontractors</h1><p>Prioritize workforce, equipment, compliance, approvals, and deployable crews before execution.</p></section>
<section class="panel"><h2>Add / Update Subcontractor</h2><form method="post" class="form-grid">
  <label>Record ID to update <input type="number" name="id" placeholder="Leave blank for new"></label><label>Organization <select name="organization_id"><?php foreach ($organizations as $o): ?><option value="<?= $o['id'] ?>"><?= htmlspecialchars($o['name']) ?></option><?php endforeach; ?></select></label>
  <label>Region <select name="region_id"><?php foreach ($regions as $r): ?><option value="<?= $r['id'] ?>"><?= htmlspecialchars($r['name']) ?></option><?php endforeach; ?></select></label>
  <label>Markets served <input name="markets_served"></label><label>Services offered <input name="services_offered" placeholder="Aerial, Underground, Fiber Splicing"></label>
  <label>Aerial crews <input type="number" name="aerial_crew_count" value="0"></label><label>Underground crews <input type="number" name="underground_crew_count" value="0"></label><label>Fiber splicing crews <input type="number" name="fiber_splicing_crew_count" value="0"></label><label>Emergency restoration crews <input type="number" name="emergency_restoration_crew_count" value="0"></label><label>Traffic control crews <input type="number" name="traffic_control_crew_count" value="0"></label>
  <label>Bucket trucks <input type="number" name="bucket_trucks" value="0"></label><label>Directional drills <input type="number" name="directional_drills" value="0"></label><label>Splicing trailers <input type="number" name="splicing_trailers" value="0"></label>
  <label>Insurance <select name="insurance_status"><?php foreach ($options['insurance'] as $o): ?><option><?= $o ?></option><?php endforeach; ?></select></label><label>W9 <select name="w9_status"><?php foreach ($options['w9'] as $o): ?><option><?= $o ?></option><?php endforeach; ?></select></label>
  <label>Approval stage <select name="approval_stage"><?php foreach ($options['approval'] as $o): ?><option><?= $o ?></option><?php endforeach; ?></select></label><label>Availability <select name="availability"><?php foreach ($options['availability'] as $o): ?><option><?= $o ?></option><?php endforeach; ?></select></label>
  <label>Performance score <input type="number" name="performance_score" min="0" max="100" value="0"></label><label class="full">Notes <textarea name="notes"></textarea></label><button class="btn">Save Subcontractor</button>
</form></section>
<?php $resource = 'subcontractors'; $recordType = 'subcontractor'; $columns = ['id'=>'ID','organization_name'=>'Organization','region_name'=>'Region','aerial_crew_count'=>'Aerial','underground_crew_count'=>'Underground','fiber_splicing_crew_count'=>'Splicing','emergency_restoration_crew_count'=>'Restoration','traffic_control_crew_count'=>'Traffic','insurance_status'=>'Insurance','w9_status'=>'W9','approval_stage'=>'Stage']; require __DIR__ . '/table.php'; ?>
